### ISSUE TITLE
Variable edit mode: access levels

### ISSUE THREAD

**Issue by sandaionescu** [ncrncornell/ced2ar#16]
In variable edit mode, there are many more “access levels” available – for the variable label, for *each* of the summary statistics, for each value, and for each frequency. There is no field or attribute in DDI for entering info at this level of granularity. And it seems unnecessary (?) Access level even for notes??? Even if somebody cared to define all these access levels, where would they go in the DDI?

**Comment by larsvilhuber** [comment]
This stems from our extended DDI, and most users may not have a need for it, but some users do (which is why we developed it). For instance, means may always be releasable when using confidential data, but extreme values never. Our Census users rely strongly on it. It has little benefit for public use data.

To read on this extension, see the notes at https://www.ncrn.cornell.edu/projects/#Extension_to_Metadata_Standards and linked pages.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by larsvilhuber** [comment]
P.S. In the case of confidential data (and a confidential codebook for confidential data), NOTES are particularly sensitive, and would need to be reviewed individually (and thus flagged individually as releasable or not) because they can leak confidential information.

The basic workflow is that you maintain a unified codebook for confidential data, and can generate a releasable (non-sensitive) version of the codebook, relying on the access level tags.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by CSimmer** [comment]
Closing.  Lars answered questions.  No development work needed.
