### ISSUE TITLE
docDscr/citation/titlStmt/titl vs. stdyDscr/citation/titlStmt/titl

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [ncrncornell/ced2ar#3]
On the list all variables page, the Codebook column lists the value of docDscr/citation/titlStmt/titl. 

I think the title you want is in stdyDscr/citation/titlStmt/titl. docDscr describes the metadata document, and is thus a good holding spot for administrative metadata; stdyDscr is meant to describe the actual study/project/dataset, and is where you want to store the metadata intended to share with the end user.

**Comment by MatthewRichardsonICPSR** [comment]
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1
https://demo.ncrn.cornell.edu/ced2ar-web/all
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/CASEID

For the ICPSR uploads, the docDscr/citation/titlStmt/titl is something along the lines of "Metadata record for ICPSR...." while the studyDscr/citation/titlStmt/titl is the real title...something like "National Survey of Blah blah blah, 1970-1980 [United States]."

In nearly all the CED2AR displays, you use docDscr/citation/titlStmt/titl as the title of the dataset instead of stdyDscr/citation/titlStmt/titl.

You can get more info on the differences between docDscr and stdyDscr on the ddialliance site:

http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation.html

docDscr
"The Document Description consists of bibliographic information describing the DDI-compliant document itself as a whole."

stdyDscr
"The Study Description consists of information about the data collection, study, or compilation that the DDI-compliant documentation file describes."

**Comment by larsvilhuber** [comment]
We discussed this, and I think there's a multi-faceted (not a simple) answer/proposal to this.

- CED2AR is codebook-focussed, so referencing (and browsing) by title of the Codebook is the right way to go. 
- ICPSR is more data focussed, so browsing by datasets is the right way to go. It just so happens that when you're on a dataset page, you view its documentation, not the data itself. 
- Editing on CED2AR is of the codebook, not the data/survey/study itself. So it makes sense on the .../vars/... page to highlight the fact that the particular variable is within a codebook (you are editing the codebook, not the data)

-> One (Solomonic) solution is to add a separate menu to the CED2AR top bar, to "Browse by study", and on THAT page, to list the stdyDscr/citation/titlStmt/titl

Some additional comments:

- on CED2AR, the codebooks we have created tend to *use* the same content for docDscr/.../titl and stdyDscr/.../titl. 
- ICPSR (or at least the DDI uploaded by Matthew) tends to have a meaningful stdyDscr/.../titl , but a relatively "mechanical" docDscr/.../titl (or nothing at all, in fact)

(cf. Citation rubrik on  https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/ssb/v/v602 and https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1 : the former has TWO citations, one of the codebook, one of the dataset; the latter has only a dataset citation)

The moral to me of that story is:

- CED2AR codebooks should be updated to have the "Codebook for" title in the docDscr/Title. (Our manually entered citations already do, so that just resolves an internal inconsistency)
- ICPSR might consider modifying their docDscr/.../titl to be more meaningful ("Metadata for Monitoring the Future: A Continuing Study of American Youth (12th-Grade Survey)" instead of "Metadata record for ICPSR02268-0005"), which I believe better describes what it is.

Separately, we might want to consider what the "short name" that would show up on the left pane is, and what it's DDI counterpart is. That left pane is probably going to disappear - it doesn't scale beyond a dozen codebooks, really, and really needs to be some sort of search pane, or classified by "first letter of study name" or "year" , or all of the above. 

Finally, Chuck and I discussed the citation itself, and I suggested that we put in a feature request to have a "citation generator" that uses all the DC elements that are already individually in the DDI, and generates a citation (in a variety of styles, and a variety of export formats) from those elements. One particular rendering of that would be hard-coded into the "citation" field during editing/generation, but would not really be relevant to the user. (it's one of my pet peeves - including that ICPSR only outputs RIS and EndNote formats, not bibtex, and only for the data, not the documentation)

**Comment by MatthewRichardsonICPSR** [comment]
"Codebook for" makes a lot more sense than "Metadata Record for"; I could change that across the board for ICPSR pretty easily.

If you're looking into dynamic citation generation, do take a look at citeproc-js/CSL. That wheel has already been invented.

**Comment by larsvilhuber** [comment]
Yes, wasn't going to reinvent the wheel, and citeproc is what I mentioned to Chuck. citeproc handles formatting the citation - does it handle exporting it in a variety of formats (bib, ris, etc.)? that's a different problem. What does ICPSR use?

**Comment by MatthewRichardsonICPSR** [comment]
ICPSR's approach is in a state of flux right now. I'm trying to move us to a citeproc-based system. Citeproc/CSL are what a lot of the bibliographic packages use under the hood. My long-term plan is to handle citations in java as citeproc Citation objects and to build utilities that convert those objects to other formats, assuming I can't find existing utilities that already do that.

Martin Fenner from DataCite is the one who clued me in to citeproc and advocates its use:

http://blog.martinfenner.org/2013/08/08/csl-is-more-than-citation-styles/

**Comment by CSimmer** [comment]
Code was deployed for the first time on demo.ncrn.cornell.edu on 1/28. Code contains the new Browse by Study pages and reading 14 configuration properties from ced2ar-web-config.properties.

Next Steps:
1) Work 2 post deployments tasks.
2) Add the documentation.
3) Modify the /config page to display the new properties.

**Comment by CSimmer** [comment]
Code was deployed on demo.ncrn.cornell.edu on 2/14.  Code contains the ability to edit the new UI configuration properties via the config page.  config.properties has browse.study=true as the default.  Updated wiki configuration page documentation with /config page screenshot.

Added patch files and instructions on 2/17.  These post deployment tasks apply to upgrading an existing environment.

**Comment by CSimmer** [comment]
This functionality will be in CED2AR version 2.8.2.0.  (2.8.2.0 will be released in the next week. This functionality is currently on demo.ncrn.cornell.edu. CDR-157)

The new functionality includes:
1. [Browse by Study](https://github.com/ncrncornell/ced2ar/wiki/User's-Guide#searching-by-study) displays a list of Study Titles (stdyDscr/citation/titlStmt/titl).     
2. Displays a codebook in a tabbed horizontal layout (Doc,Study,File,Data,Other Material).
3. A [site administrator](https://github.com/ncrncornell/ced2ar/wiki/The-CED2AR-Configuration-Files#ui-navigation-customization) can:      
- Enable one or both Browse by tabs. 
- Change the name of the browse tabs to suite the site’s needs. 
- Browse by Study subtabs can also be turned on/off and the tab names can be changed.

**Comment by CSimmer** [comment]
The demo and dev systems were upgraded to 2.8.2.0 on 6-Mar-2017.

Closing out this issue. (jira CDR-157)
