### ISSUE TITLE
can't see crowdsourced edits; official version unviewable

### ISSUE THREAD

**Issue by MatthewRichardsonICPSR** [ncrncornell/ced2ar#8]
Sanda made some variable edits on a codebook I uploaded:

"I've made the following edits to metadata for 02268:
study level - added distributor URL; added one related publication
variable 4101 - added concept, vocab list, vocab list URL; edited value labels (to full text)
let me know."

So I went to Browse by Codebook
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks

and clicked on "Metadata record for ICPSR02268-0005"
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1

It says that I'm looking at the crowdsourced metadata. The "git" button on the upper right has a hover label saying "View variables changed". Clicking on that produces a message stating "No variable commits found."

So I then tried clicking on the "official version" link atop the codebook page, only to get an error message:

ERROR: Codebook with handle 'icpsr02268-0001v1' does not exist 

Did I miss a step somewhere in publishing the file?

**Comment by CSimmer** [comment]
Hi Matthew,

I can't answer the question about "publishing the file", but we do have an issue on demo with pushing changes out.  That is probably the reason you're not seeing the changes.  We are working on the issue.

**Comment by sandaionescu** [comment]
We repeated this test with a file uploaded by Sanda (ANES 1952) and edits made by Jared. Got the same results as those described by Matthew in his post. Can you please let us know when you've fixed the problem, so that we can test again?

**Comment by CSimmer** [comment]
We do have a problem our VersionControl.taskCommitRepo() process on demo.  There is a fix for the problem in the upcoming release.  The release will be available in the next week.  demo will be upgraded as soon as the release is available.  

Hopefully this will resolve your issue.

**Comment by Kbrums** [comment]
Are you able to see the changes when you look at the title page and variable pages that were edited (regardless of what the git status says)?

**Comment by CSimmer** [comment]
demo was upgraded to the next release (2.8.2.0) this morning.

(The VersionControl.taskCommitRepo process is not erroring out as it did before.)

After answering Kyle's question, you should be able to test again.

**Comment by sandaionescu** [comment]
Hello. In answer to Kyle's question I asked Matthew to re-verify if he can see the changes I've made to a file owned by him. He can see the changes as described by me to him only when he is logged in and in edit mode. But there is nothing that indicates that those are changes to the original metadata, and about who submitted them and when, and that they need to be approved (by him, the owner). When clicking on "Compare changes" he and I see a bunch of highlighted fields, but no indication of what was changed. The highlighted fields are both original fields,  and fields added or edited by me. This is under "Current", on the right hand side of the screen. On the left side of the screen there is a column-type entry labeled "Remote" that is completely blank. Here is Matthew's  answer as of 10:30 this morning: 
"I can't see any changes. So I went to the codebook for 2268: https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1
There's a button that says "git: view variables changed". That takes me to a page that says "No variable commits found."
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/versions2
From that first URL, there's a link titled: "view the official version". That link points to:
https://dev.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1
And returns an error message: "ERROR: Codebook with handle 'icpsr02268-0001v1' does not exist"
I didn't receive any email notifications of changes. If I go **directly to the variable you indicated:**
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101
I do see a link atop the page that says:
You are viewing crowdsourced metadata. View the official version or compare the changes .
The "compare the changes" link implies you added summary statistics, in addition to the changes you described above. The "official version" link still doesn't work.

**Comment by larsvilhuber** [comment]
OK, just a clarification, now that I understand the context better:

* the crowdsourcing functionality relies EXCLUSIVELY on cross-server setup. You cannot "crowdsource" locally.
* the "compare changes" functionality identifies changes ACROSS servers. The codebook has to exist across all servers.

In the base setup, there is a two or three server setup:

- wiki = crowdsourcing
- dev = closed editing
- prod = published versions

Users browse prod, can make edits on wiki
(codebook) Developers can make edits on dev, can pull in changes from wiki (that's what you would see on the "view changes page" - it fails if there is no remote version to point to. THAT'S A FEATURE. (Note: and it needs to improve the documentation on this - CHUCK)

That being said, *local* changes should also show up in the commits. Those are the red fields you see. But the "view changes" page is set up to compare to the remote server, not between revisions of the local one. (That can presumably be configured, but is not the same).

That being said, there does seems to be a bug in viewing the remote repository. If I look at https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101, I see changes highlighted. But to see the exact changes as *locally* versioned, the link to the repository at https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/versions2 (which points to https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/2875c51a0b8f74a96325b3751e692143cad3a83c) seems to be broken. That's a BUG.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by sandaionescu** [comment]
When you look at https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101, not all of the changes are highlighted. The concept is highlighted, but I also edited the value labels.

Also, forgive me if this is a silly question, but why would only the cross-server changes be documented?  To contribute, edit, add to the metadata one has to have a server? If I'm a researcher, I can upload codebooks on your server, and then it cannot be edited by someone who does not have a server?

**Comment by larsvilhuber** [comment]
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101/diff shows the edited value labels.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by sandaionescu** [comment]
No, sorry, but it shows a lot of highlighted fields, including unedited fields, and edited fields. There is no information about what was changed, specifically. The labels are displayed as edited even in the normal view, but there is no indication that they have been edited post-upload.

**Comment by larsvilhuber** [comment]
Understood.

The current "changes" view was optimized for viewing changes between the remote server (which is not populated in your case) and the server you are on (demo). Tracing this through may show that there are some "high-level" flags that lead to the overly-enthusiastic highlighting (i.e., if any label was edited, all labels are highlighted). This might work better if the remote server were populated.

We have mulled both "collaborative" and "crowd-sourced" editing. The latter got some of the more recent efforts in programming. You may be highlighting some shortcomings that choice imposed on the former...

lars

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by Kbrums** [comment]
1. The highlighted changes show the difference between the most recent commit to the repository, and the one previous. The currently highlighted changes are showing the difference between when there was no codebook, and when the codebook was uploaded, i.e. everything is a 'difference'. There is a version control bug that we are sorting out now that should fix this issue of the recent changes not showing up. So hopefully soon you will see the difference between the initial upload and the changes you just made.

2. The question that I have still remains. I am trying to identify if there is an editing bug in addition to the version control bug. When you, Sanda, edit a field on the demo server and you click 'save', does the field actually change on the web interface right there? I.e. on 
https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101
if you edit any field trivially, does it show up on that page right after you save, or does it remain unchanged?

**Comment by sandaionescu** [comment]
2. in response to 2. above, yes, the changes I made do show on: https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101. The change I made today is highlighted in blue. The previous changes I made are not highlighted, but they do show.

1. in response to 1. above, I think "differences" at field level should not be shown (at least not to a user, or editor) from when there is nothing (i.e. no codebook) to when there is *something* (i.e. the initial codebook upload) - but only when a change is made to the first/original instance of a codebook. Otherwise it is confusing.

**Comment by CSimmer** [comment]
Because of the number of url's, errors, fixes and requests listed to-date, I ran some simple pass/fail tests this morning to narrow down on what still needs to be worked.

I tested all the url's listed in this issue.  The possible outcomes are:

- **Pass** = Page displays data.  Passing is assumed and not listed below.
- **FAIL** = Error is displayed.  Only FAIL's are listed in the test results below.

At the bottom are the list of FAIL's with comments.

Test Start: 03/07/2017 09:40 AM

**MatthewRichardsonICPSR 17-Feb**
  https://demo.ncrn.cornell.edu/ced2ar-web/codebooks
  https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1
    PASS, but NO git button.
    Click Login icon (as authorized user) 
      ORCID used to authorize
    https://demo.ncrn.cornell.edu/ced2ar-web/edit/codebooks/icpsr02268-0001/v/v1/  redisplayed
      Click git icon
        https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/versions2  displayed
          Modified Variables page displays displays two rows for V4101
            V4101	March 6, 2017 at 11:05 AM	View commit	sandai@umich.edu	Remote Change
            V4101	March 6, 2017 at 10:06 AM	View commit	lyle@umich.edu	Remote Change
          Click row 1 View commit
            https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/cc9616ffcf17e5f23b8b34311f57111b818dbf75   displayed in new tab
          Click previous tab
          Click row 2 View commit
            https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/2875c51a0b8f74a96325b3751e692143cad3a83c   displayed in new tab
    https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1  (back button, in edit mode)
      Click link: official version  (https://dev.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1)
        **FAIL #1** - Link fails.  Codebook with handle 'icpsr02268-0001v1' does not exist on DEV (closed editing)
          redirected to: https://dev.ncrn.cornell.edu/ced2ar-web/search
            **FAIL #2** - ERROR: Codebook with handle 'icpsr02268-0001v1' does not exist    displayed in pop up
  
  
**sandaionescu 6-Mar** reply uses most of the url's listed in the intial issue.  Except, for:
  https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101
      Click link: official version  (https://dev.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101)
        **FAIL #3** - Link fails.  Codebook with handle 'icpsr02268-0001v1' does not exist on DEV (closed editing)
          redirected to: https://dev.ncrn.cornell.edu/ced2ar-web/search
            **FAIL #4** - ERROR: Codebook with handle 'icpsr02268-0001v1' does not exist    displayed in pop up
      Click link: compare the changes   (https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101/diff)
        Page displays.  Remote side is empty.  Current has most values in red.
        Nothing about "link implies you added summary statistics".  Addding as ITEM #1

**FAIL Summary:**

- FAIL #1 - Looks like the correct response under the current set up with ICPSR testing.  There is no codebook starting with icpsr02268 on DEV.  See 6-Mar replies from larsvilhuber (crowdsourcing; closed editing; the remote server is not populated in your case). 
- FAIL #2 - Looks like correct response under current set up with ICPSR testing.  
- FAIL #3 - See: FAIL #1.  This is at the var level which is lower than FAIL #1.
- FAIL #4 - See: FAIL #2.

**Comment by CSimmer** [comment]
List of outstanding Action Items from issue discussion. 

**ITEM #1 - (6-Mar) sandaionescu** is asking about summary statistics on the var Differences page (Ex: https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101/diff).  
  **QUESTION:** Lars, do you want to add some sort of statistics to this page?  If so, what are they?

**ITEM #2 - (6-Mar) larsvilhuber** wants Chuck to improve documentation on:
Users browse prod, can make edits on wiki (codebook), Developers can make edits on dev, can pull in changes from wiki (that's what you would see on the "view changes page" - it fails if there is no remote version to point to.  THAT'S A FEATURE. (Note: and it needs to improve the documentation on this - CHUCK)

**ITEM #3 - (6-Mar) larsvilhuber:** "That being said, *local* changes should also show up in the commits. Those are the red fields you see. But the "view changes" page is set up to compare to the remote server, not between revisions of the local one. (That can presumably be configured, but is not the same)."
  **QUESTION:** Do the following "view commit" pages statisfy this item?  They are showing local commits since there is no other servers containing this xml document.
    https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/vars/V4101/versions
      view commit link: https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/cc9616ffcf17e5f23b8b34311f57111b818dbf75
    https://demo.ncrn.cornell.edu/ced2ar-web/codebooks/icpsr02268-0001/v/v1/versions2
      view commit link: https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/cc9616ffcf17e5f23b8b34311f57111b818dbf75
      view commit link: https://bitbucket.org/ced2ar/ced2ar-demo.git/commits/2875c51a0b8f74a96325b3751e692143cad3a83c

**ITEM #4 - (6-Mar) sandaionescu** "in response to 1. above, I think "differences" at field level should not be shown (at least not to a user, or editor) from when there is nothing (i.e. no codebook) to when there is something (i.e. the initial codebook upload) - but only when a change is made to the first/original instance of a codebook. Otherwise it is confusing."
  **Discussion:** Two items to consider.  
    1) This is a little different behavior than the way git determines changes.  It may cause an unintended side effects.
    2) It don't think there is a way to determine if this is the first change.  I don't think there is an element to store this data.
  **QUESTION**: Lars, do you want me to add this as an enhancement request?

All,
   Please any corrections you think are needed.

**Comment by sandaionescu** [comment]
Hi,
Re: ITEM #1 above; I do not recall asking for that. I asked for values to show (in addition to value labels) on the variables comparison page. Also, more generally, I *do not* care very much for summary statistics. But I think category-level frequencies *should* be displayed both on the individual variable description page and the variables comparison page.

**Comment by MatthewRichardsonICPSR** [comment]
Lars, my instructions to Jared/Sanda were a bit flawed as I didn't understand the cross-server nature of the crowdsourcing setup. 

For them to really test the crowdsourcing, I need to upload the same file to both your demo server and your dev server. Is there anything else I would need to do? I want Sanda to see how the experience works for a crowdsource user with me as the codebook creator so that we can see how the flow of edits works.

**Comment by larsvilhuber** [comment]
We discussed this in our weekly meeting. Our current implementation inadequately works for the "small workgroup" setting, and we are investigating how to fix that. We are also updating the documentation to make these two scenarios clearer. We are also making the labeling of the "remote" and "current" better - that has been a known issue.

otherwise, your description is right: upload to dev.ncrn.cornell.edu, and treat dev.ncrn as the master/official, and demo.ncrn as the "crowdsourced edits". You might need the relevant permissions - somebody on the team should be able to help you with that.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by Kbrums** [comment]
Matthew, I've added you as an admin on the dev server.

**Comment by CSimmer** [comment]
Re: (8-Mar) sandaionescu: Re: ITEM #1 
The misunderstanding is my fault.  You listed the Variable page for V4101 (.../vars/V4101)  I listed the Variable Difference page (.../vars/V4101/diff).  Sorry, I posted the wrong url. 

I will open up a new issue for your category-level frequencies enhancement request.  That way, it won't get lost in this issue.

Field labels have been brought up in multiple issues.  They will be handled separately from the other issues.  We developing an overall solution for v2.

**Comment by CSimmer** [comment]
Disposition of Action Items from issue discussion.

**ITEM #1 - (6-Mar) sandaionescu:** Moved to Add category-level frequencies to variable pages. #28
**ITEM #2 - (6-Mar) larsvilhuber:** Created jira issue: CDR-188  Document deployment scenarios in high level business/user terms
**ITEM #3 - (6-Mar) larsvilhuber:** Created jira issue: CDR-185  Rework the version control viewing/diffing
**ITEM #4 - (6-Mar) sandaionescu:** Moved to Change variable differences page behavior. #29

**Comment by CSimmer** [comment]
Closing.
